services:
  # Django Service
  django:
    container_name: django_hellowlab
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./HellowLab/media:/app/media               # Mount media folder
    environment:
      - DEBUG=false
      - DJANGO_DEBUG=False
      - DJANGO_DB_NAME=hellowlab_db
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    networks:
      - backend
    restart: unless-stopped

  # PostgreSQL Service
  db:
    container_name: hellowlab_db
    image: postgres:latest
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data  # Mount the database data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hellowlab_db
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: 'nginx:latest'  # Use the official Nginx image
    container_name: nginx
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./HellowLab/media:/var/www/media           # Mount media folder
      - ./nginx/data:/data                         # For storing log data
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Custom Nginx config
      - ./nginx/sites-enabled:/etc/nginx/conf.d    # Mount custom site configs
      - ./nginx/ssl:/etc/ssl                       # SSL certificates
    networks:
      - backend
      - frontend
    restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  backend:
  frontend:
