services:
  # Django Service
  django:
    container_name: django_hellowlab
    build: .
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./HellowLab/media:/app/media
    environment:
      - DEBUG=false
      - DJANGO_DEBUG=False
      - DJANGO_DB_NAME=hellowlab_db
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
    networks:
      - backend
    restart: unless-stopped

  # PostgreSQL Service
  db:
    container_name: hellowlab_db
    image: postgres:latest
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hellowlab_db
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

  # NGINX Proxy Manager Service
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # NGINX Proxy Manager UI
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./nginx_proxy_data:/data
      - ./nginx_proxy_letsencrypt:/etc/letsencrypt
    networks:
      - backend
      - frontend
    restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  backend:
  frontend:
