# Generated by Django 5.0.2 on 2024-08-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imdbResult', models.CharField(max_length=30)),
                ('swipeResult', models.BooleanField()),
                ('swipeDate', models.DateTimeField(auto_now_add=True)),
                ('watched', models.BooleanField(default=False)),
                ('myRanking', models.IntegerField(blank=True, null=True)),
                ('myComments', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
