# Generated by Django 5.0.2 on 2024-08-10 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieresult',
            old_name='swipeResult',
            new_name='liked',
        ),
        migrations.RenameField(
            model_name='movieresult',
            old_name='imdbResult',
            new_name='tmdb_result',
        ),
        migrations.AddField(
            model_name='movieresult',
            name='movie_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
