# Generated by Django 5.0.2 on 2024-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0005_rename_movie_name_movieresult_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieresult',
            name='myComments',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
