# Generated by Django 5.0.2 on 2024-08-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0007_alter_movieresult_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieresult',
            name='myComments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieresult',
            name='myRanking',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
