# Generated by Django 5.0.2 on 2024-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0009_alter_movieresult_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieresult',
            name='liked',
            field=models.PositiveIntegerField(choices=[(0, 'Liked'), (1, 'Disliked'), (2, 'Empty')], default=0),
        ),
    ]
