# Generated by Django 5.0.2 on 2024-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0011_alter_movieresult_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieresult',
            name='myRanking',
        ),
        migrations.AddField(
            model_name='movieresult',
            name='myRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
