# Generated by Django 5.0.2 on 2024-08-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblfeature', '0013_tmdbindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbindex',
            name='popular_date',
            field=models.DateField(),
        ),
    ]
