name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@146.190.185.97 << 'EOF'
            cd HellowLabBackend_Django

            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > HellowLab/HellowLab/.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> HellowLab/HellowLab/.env
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> HellowLab/HellowLab/.env
            echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> HellowLab/HellowLab/.env
            echo "DJANGO_DB_USER=${{ secrets.DJANGO_DB_USER }}" >> HellowLab/HellowLab/.env
            echo "DJANGO_DB_PASSWORD=${{ secrets.DJANGO_DB_PASSWORD }}" >> HellowLab/HellowLab/.env
            echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> hellowlab/hellowlab/.env
            echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> HellowLab/HellowLab/.env
            echo "JWT_SIGNING_KEY=${{ secrets.JWT_SIGNING_KEY }}" >> HellowLab/HellowLab/.env

            git checkout main
            git pull origin main
            sudo docker compose up -d --build --remove-orphans
          EOF
