name: Deploy to VPS

on:
  push:
    branches:
      - mango_working_branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@159.89.227.220 << 'EOF'
            cd HellowLabBackend_Django
            git pull origin mango_working_branch
            sudo docker-compose up -d --build --remove-orphans
          EOF
